---
language: ruby
script: bundle exec rake spec:$SUITE
bundler_args: --without=vagrant
rvm:
  - ruby-2.1.3
notifications:
  email:
    recipients:
    - drnicwilliams@gmail.com
    on_success: change
    on_failure: always
env:
  matrix:
  - SUITE=unit
  - SUITE=integration:aws:basic
  global:
    secure: "e1M3OQJfiqM7V1IPqwRZNUlw53Kl+6nTo6CbfcGu5+hTtutnh0n0t9DZjYxz\nYwgawuxXKzQfbBi5sYoMPBgKylR3JT7GKjIVRm+bA+jip3wmBjXAmT/DlFNQ\nKmtiMG0kXitHfVnG6imz2wUWikbEdjCzji1+9LV33Y6JGBkD+90="
